### ISSUE TITLE
跳转activity组件 有demo吗

### ISSUE THREAD

**Issue by zhxacg** [WrBug/componentrouter#2]

**Comment by WrBug** [comment]
我们目前并没有提供Activity的跳转，目前市面上已经有很多比较成熟的路由框架了，比如arouter，
componentrouter你可以看成是一种跨组件方法调用的扩展，关于配合第三方框架使用你可以参考下：

[使用3. (结合第三方框架)](https://github.com/WrBug/componentrouter#%E4%BD%BF%E7%94%A83-%E7%BB%93%E5%90%88%E7%AC%AC%E4%B8%89%E6%96%B9%E6%A1%86%E6%9E%B6)
